stages: # List of stages for jobs, and their order of execution
  - deploy

push-to-github:
  stage: deploy
  tags:
    - docker
  only:
    - main
  image: ubuntu:latest
  before_script:
    - apt-get clean
    - apt-get update -y && apt-get install -y openssh-client git
    - mkdir -p /root/.ssh && chmod 700 /root/.ssh
    - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add /root/.ssh/id_rsa
  script:
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git checkout -b main
    - git remote set-url origin ${GITHUB_REPO}
    - git push --force origin main

push-to-gitlab:
  stage: deploy
  tags:
    - docker
  only:
    - main
  image: ubuntu:latest
  before_script:
    - apt-get clean
    - apt-get update -y && apt-get install -y openssh-client git
    - mkdir -p /root/.ssh && chmod 700 /root/.ssh
    - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add /root/.ssh/id_rsa
  script:
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git checkout -b main
    - git remote set-url origin ${GITEE_REPO}
    - git push --force origin main
